#!/bin/bash

# Author: Patryk Kazmierczak
# Date Created: 07/06/2023
# Last Modified: 07/06/2023

# Description
# Prints "Backup for all files in directory" 

# Usage
# backup_script

tar -cvf ~/bash_course/my_backup_"$(date +%d-%m-%Y_%H-%M-%S)".tar ~/* 2>/dev/null

exit 0
